### PR TITLE
feat: Specific payment events

### PR DESCRIPTION
**Pull request by remipelhate**
For more info on this feature, please have a look at the `docs/resource-specific-events.md` file added in this PR.

### CODE REVIEW

**Comment by remipelhate** [comment]
@ppelgrims @edwwaarrdd I've got a little bit more polishing to do here, but I think the overall concept works rather well. I would highly appreciate some feedback :) Could you guys have a look at the docs file and EPC added in this PR and let me know if you like the approach? Does it provide enough value? Are we missing something? ...

I want to tackle refunds with a pretty much identical API, but I don't want to start on it without knowing what you guys think of it.

**Review by ppelgrims — APPROVED** [review]

**Comment by edwwaarrdd** [comment]
Little late to the party... 😅 
but maybe somewhere clearly state that this will only work for the Payments API and not the Orders api from mollie.
I'm not quite sure but do we also need to listen to the `authorized` event from mollie?
Also are we sure the prefix for the ID will always be tr_?

**Comment by ppelgrims** [comment]
> but maybe somewhere clearly state that this will only work for the Payments API and not the Orders api from mollie.

I'll probably make a PR this week

> I'm not quite sure but do we also need to listen to the `authorized` event from mollie?

That should probably be included

> Also are we sure the prefix for the ID will always be tr_?

It is for `"mollie/mollie-api-php": "^2.26"`

**Comment by remipelhate** [comment]
Hi @edwwaarrdd! Thanks for the feedback mate. Let's see...

> but maybe somewhere clearly state that this will only work for the Payments API and not the Orders api from mollie.

As @ppelgrims says, the idea is to add support for the Orders API. But this PR is already rather massive so we should do so through a separate PR.

> I'm not quite sure but do we also need to listen to the authorized event from mollie?

In my original idea, we shouldn't. If you look at the [webhook docs](https://docs.mollie.com/guides/webhooks), Mollie only calls the webhook for a status change if it reaches `paid`, `expired`, `failed` or `canceled`. It does not call the webhook when the status switches to `authorized`. So if the webhook is called and the status is `authorized`, it means something else changed on the payment. My idea was to reflect that exact behaviour. We want to replicate the reason why Mollie calls the webhook.

The same applies for refunds. Mollie only calls the payment webhook when the refund was actually transferred to the customer (I confirmed this with their support line). So the only emit a refund event when the refund status is `refunded`.

Do you guys agree with this approach? It makes sense to me, but it's certainly open for discussion. If we continue with this approach, we should explicitly document it for sure to avoid any confusion.

> Also are we sure the prefix for the ID will always be tr_?

Excellent question! I've always known payment ID's to be prefixed with `tr_`. If I go through their SDK history, it looks like the `PaymentEndpoint` has been requiring this prefix for 3 years already. So I think we're good, no?

**Comment by edwwaarrdd** [comment]
@remipelhate 
You are correct the `authorized` state is not used for the webshooks on the Payments API but it is used for the Orders API, that is for the other PR 😄 
And yeah I checked their own php library and they also enforce that a payment id starts with TR_
see: https://github.com/mollie/mollie-api-php/blob/619349868112df2825d7a225d4e92f9fb7e9f2d8/src/Endpoints/PaymentEndpoint.php#L67

Looks good 👍

**Pull request merged**
